version = 1

test_patterns = ["app/**/*.ts*"]

exclude_patterns = [
    "**/__tests__/**.test.ts*",
    "**/*.d.ts",
    "node_modules/"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
