/* eslint-disable */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded date */
  ISO8601Date: { input: any; output: any; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: any; output: any; }
};

export type AnyResource = {
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
};

/** Autogenerated return type of Apple. */
export type ApplePayload = {
  __typename?: 'ApplePayload';
  authenticatable?: Maybe<User>;
  /**
   * Authentication credentials. Null if after signUp resource is not active for
   * authentication (e.g. Email confirmation required).
   */
  credentials?: Maybe<Credential>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of CreateDropzone */
export type CreateDropzoneInput = {
  attributes: DropzoneInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateDropzone. */
export type CreateDropzonePayload = {
  __typename?: 'CreateDropzonePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzone?: Maybe<Dropzone>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of CreateExtra */
export type CreateExtraInput = {
  attributes: ExtraInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of CreateExtra. */
export type CreateExtraPayload = {
  __typename?: 'CreateExtraPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  extra?: Maybe<Extra>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of CreateGhost */
export type CreateGhostInput = {
  attributes: GhostInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateGhost. */
export type CreateGhostPayload = {
  __typename?: 'CreateGhostPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  user?: Maybe<User>;
};

/** Autogenerated input type of CreateLoad */
export type CreateLoadInput = {
  attributes: LoadInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateLoad. */
export type CreateLoadPayload = {
  __typename?: 'CreateLoadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  load?: Maybe<Load>;
};

/** Autogenerated input type of CreateOrder */
export type CreateOrderInput = {
  attributes: OrderInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateOrder. */
export type CreateOrderPayload = {
  __typename?: 'CreateOrderPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  order?: Maybe<Order>;
};

/** Autogenerated input type of CreatePlane */
export type CreatePlaneInput = {
  attributes: PlaneInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreatePlane. */
export type CreatePlanePayload = {
  __typename?: 'CreatePlanePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  plane?: Maybe<Plane>;
};

/** Autogenerated input type of CreateRig */
export type CreateRigInput = {
  attributes: RigInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated input type of CreateRigInspection */
export type CreateRigInspectionInput = {
  attributes: RigInspectionInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of CreateRigInspection. */
export type CreateRigInspectionPayload = {
  __typename?: 'CreateRigInspectionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  rigInspection?: Maybe<RigInspection>;
};

/** Autogenerated return type of CreateRig. */
export type CreateRigPayload = {
  __typename?: 'CreateRigPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  rig?: Maybe<Rig>;
};

/** Autogenerated input type of CreateSlot */
export type CreateSlotInput = {
  attributes: SlotInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateSlot. */
export type CreateSlotPayload = {
  __typename?: 'CreateSlotPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  slot?: Maybe<Slot>;
};

/** Autogenerated input type of CreateSlots */
export type CreateSlotsInput = {
  attributes: SlotInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateSlots. */
export type CreateSlotsPayload = {
  __typename?: 'CreateSlotsPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  load?: Maybe<Load>;
};

/** Autogenerated input type of CreateTicket */
export type CreateTicketInput = {
  attributes: TicketTypeInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateTicket. */
export type CreateTicketPayload = {
  __typename?: 'CreateTicketPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  ticketType?: Maybe<TicketType>;
};

/** Autogenerated input type of CreateWeatherCondition */
export type CreateWeatherConditionInput = {
  attributes: WeatherConditionInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of CreateWeatherCondition. */
export type CreateWeatherConditionPayload = {
  __typename?: 'CreateWeatherConditionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  weatherCondition?: Maybe<WeatherCondition>;
};

export type Credential = {
  __typename?: 'Credential';
  accessToken: Scalars['String']['output'];
  client: Scalars['String']['output'];
  expiry: Scalars['Int']['output'];
  tokenType: Scalars['String']['output'];
  uid: Scalars['String']['output'];
};

/** Autogenerated input type of DeleteDropzone */
export type DeleteDropzoneInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteDropzone. */
export type DeleteDropzonePayload = {
  __typename?: 'DeleteDropzonePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzone?: Maybe<Dropzone>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of DeleteLoad */
export type DeleteLoadInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteLoad. */
export type DeleteLoadPayload = {
  __typename?: 'DeleteLoadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  load?: Maybe<Load>;
};

/** Autogenerated input type of DeletePlane */
export type DeletePlaneInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeletePlane. */
export type DeletePlanePayload = {
  __typename?: 'DeletePlanePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  plane?: Maybe<Plane>;
};

/** Autogenerated input type of DeleteRig */
export type DeleteRigInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteRig. */
export type DeleteRigPayload = {
  __typename?: 'DeleteRigPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  rig?: Maybe<Rig>;
};

/** Autogenerated input type of DeleteSlot */
export type DeleteSlotInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteSlot. */
export type DeleteSlotPayload = {
  __typename?: 'DeleteSlotPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  slot?: Maybe<Slot>;
};

/** Autogenerated input type of DeleteTicket */
export type DeleteTicketInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteTicket. */
export type DeleteTicketPayload = {
  __typename?: 'DeleteTicketPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  ticketType?: Maybe<TicketType>;
};

/** Autogenerated input type of DeleteUser */
export type DeleteUserInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** The ID of the dropzone user to delete */
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of DeleteUser. */
export type DeleteUserPayload = {
  __typename?: 'DeleteUserPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

export type Dropzone = AnyResource & Wallet & {
  __typename?: 'Dropzone';
  allowedJumpTypes: Array<JumpType>;
  banner?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  currentConditions: WeatherCondition;
  /** The caller's membership of this dropzone, or null if they have not joined it (see joinDropzone) */
  currentUser?: Maybe<DropzoneUser>;
  dropzoneUser?: Maybe<DropzoneUser>;
  extras: Array<Extra>;
  federation: Federation;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  isCreditSystemEnabled: Scalars['Boolean']['output'];
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
  /** Get the master log entry for a given date */
  masterLog: MasterLog;
  name?: Maybe<Scalars['String']['output']>;
  orders?: Maybe<OrderConnection>;
  planes: Array<Plane>;
  primaryColor?: Maybe<Scalars['String']['output']>;
  purchases?: Maybe<OrderConnection>;
  rigInspectionTemplate?: Maybe<FormTemplate>;
  /** Get rigs for dropzone */
  rigs?: Maybe<Array<Rig>>;
  roles: Array<UserRole>;
  sales?: Maybe<OrderConnection>;
  secondaryColor?: Maybe<Scalars['String']['output']>;
  settings?: Maybe<Settings>;
  state: DropzoneState;
  statistics: Statistics;
  ticketTypes: Array<TicketType>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  userRoles: Array<UserRole>;
  walletId: Scalars['ID']['output'];
};


export type DropzoneAllowedJumpTypesArgs = {
  userId: Array<Scalars['Int']['input']>;
};


export type DropzoneDropzoneUserArgs = {
  id?: InputMaybe<Scalars['Int']['input']>;
  userId?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneMasterLogArgs = {
  date: Scalars['Int']['input'];
};


export type DropzoneOrdersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  startDate?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzonePurchasesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneRolesArgs = {
  selectable?: InputMaybe<Scalars['Boolean']['input']>;
};


export type DropzoneSalesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneTicketTypesArgs = {
  isPublic?: InputMaybe<Scalars['Boolean']['input']>;
};

/** The connection type for Dropzone. */
export type DropzoneConnection = {
  __typename?: 'DropzoneConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<DropzoneEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Dropzone>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type DropzoneEdge = {
  __typename?: 'DropzoneEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Dropzone>;
};

export type DropzoneInput = {
  banner?: InputMaybe<Scalars['String']['input']>;
  federation?: InputMaybe<Scalars['Int']['input']>;
  isCreditSystemEnabled?: InputMaybe<Scalars['Boolean']['input']>;
  isPublic?: InputMaybe<Scalars['Boolean']['input']>;
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
  name: Scalars['String']['input'];
  primaryColor?: InputMaybe<Scalars['String']['input']>;
  requestPublication?: InputMaybe<Scalars['Boolean']['input']>;
  secondaryColor?: InputMaybe<Scalars['String']['input']>;
  /** Settings for the dropzone */
  settings?: InputMaybe<SettingsInput>;
};

export enum DropzoneState {
  Archived = 'archived',
  Demo = 'demo',
  InReview = 'in_review',
  Private = 'private',
  Public = 'public'
}

export enum DropzoneStateEvent {
  /** archive */
  Archive = 'archive',
  /** demo */
  Demo = 'demo',
  /** publish */
  Publish = 'publish',
  /** request_publication */
  RequestPublication = 'request_publication',
  /** unpublish */
  Unpublish = 'unpublish'
}

export type DropzoneUser = AnyResource & Wallet & {
  __typename?: 'DropzoneUser';
  /** Get user rigs that have been inspected and marked as OK + dropzone rigs */
  availableRigs?: Maybe<Array<Rig>>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  credits?: Maybe<Scalars['Int']['output']>;
  dropzone: Dropzone;
  expiresAt?: Maybe<Scalars['Int']['output']>;
  guid: Scalars['ID']['output'];
  hasCredits: Scalars['Boolean']['output'];
  hasExitWeight: Scalars['Boolean']['output'];
  hasLicense: Scalars['Boolean']['output'];
  hasMembership: Scalars['Boolean']['output'];
  hasReserveInDate: Scalars['Boolean']['output'];
  hasRigInspection: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  jumpTypes?: Maybe<Array<JumpType>>;
  license?: Maybe<License>;
  notifications?: Maybe<NotificationConnection>;
  orders?: Maybe<OrderConnection>;
  permissions?: Maybe<Array<Permission>>;
  purchases?: Maybe<OrderConnection>;
  rigInspections?: Maybe<Array<RigInspection>>;
  role?: Maybe<UserRole>;
  sales?: Maybe<OrderConnection>;
  slots?: Maybe<SlotConnection>;
  unseenNotifications: Scalars['Int']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
  user: User;
  userFederation?: Maybe<UserFederation>;
  walletId: Scalars['ID']['output'];
};


export type DropzoneUserAvailableRigsArgs = {
  isTandem?: InputMaybe<Scalars['Boolean']['input']>;
  loadId?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneUserNotificationsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneUserOrdersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  startDate?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneUserPurchasesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneUserSalesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type DropzoneUserSlotsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};

/** The connection type for DropzoneUser. */
export type DropzoneUserConnection = {
  __typename?: 'DropzoneUserConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<DropzoneUserEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<DropzoneUser>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type DropzoneUserEdge = {
  __typename?: 'DropzoneUserEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<DropzoneUser>;
};

export type DropzoneUserInput = {
  credits?: InputMaybe<Scalars['Float']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  exitWeight?: InputMaybe<Scalars['Float']['input']>;
  expiresAt?: InputMaybe<Scalars['Int']['input']>;
  federationNumber?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  license?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  nickname?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  pushToken?: InputMaybe<Scalars['String']['input']>;
  userRoleId?: InputMaybe<Scalars['Int']['input']>;
};

export type Event = {
  __typename?: 'Event';
  action?: Maybe<EventAction>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  createdBy?: Maybe<DropzoneUser>;
  details?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  level?: Maybe<EventLevel>;
  message?: Maybe<Scalars['String']['output']>;
  resource?: Maybe<AnyResource>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export enum EventAccessLevel {
  /** admin */
  Admin = 'admin',
  /** system */
  System = 'system',
  /** user */
  User = 'user'
}

export enum EventAction {
  /** assigned */
  Assigned = 'assigned',
  /** confirmed */
  Confirmed = 'confirmed',
  /** created */
  Created = 'created',
  /** deleted */
  Deleted = 'deleted',
  /** updated */
  Updated = 'updated'
}

/** The connection type for Event. */
export type EventConnection = {
  __typename?: 'EventConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<EventEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Event>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type EventEdge = {
  __typename?: 'EventEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Event>;
};

export enum EventLevel {
  /** debug */
  Debug = 'debug',
  /** error */
  Error = 'error',
  /** info */
  Info = 'info'
}

export type Extra = AnyResource & SellableItem & {
  __typename?: 'Extra';
  cost: Scalars['Float']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone: Dropzone;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  ticketTypes: Array<TicketType>;
  title?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type ExtraInput = {
  cost?: InputMaybe<Scalars['Float']['input']>;
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  ticketTypeIds?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/** Autogenerated return type of Facebook. */
export type FacebookPayload = {
  __typename?: 'FacebookPayload';
  authenticatable?: Maybe<User>;
  /**
   * Authentication credentials. Null if after signUp resource is not active for
   * authentication (e.g. Email confirmation required).
   */
  credentials?: Maybe<Credential>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

export type Federation = {
  __typename?: 'Federation';
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  licenses?: Maybe<Array<License>>;
  name?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type FieldError = {
  __typename?: 'FieldError';
  field: Scalars['String']['output'];
  message: Scalars['String']['output'];
};

/** Autogenerated input type of FinalizeLoad */
export type FinalizeLoadInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
  state: LoadState;
};

/** Autogenerated return type of FinalizeLoad. */
export type FinalizeLoadPayload = {
  __typename?: 'FinalizeLoadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  load?: Maybe<Load>;
};

export type FormTemplate = {
  __typename?: 'FormTemplate';
  createdAt: Scalars['ISO8601DateTime']['output'];
  definition?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type FormTemplateInput = {
  definition?: InputMaybe<Scalars['String']['input']>;
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type GeocodedLocation = {
  __typename?: 'GeocodedLocation';
  formattedString?: Maybe<Scalars['String']['output']>;
  id?: Maybe<Scalars['ID']['output']>;
  lat?: Maybe<Scalars['Float']['output']>;
  lng: Scalars['Float']['output'];
};

export type GhostInput = {
  dropzone: Scalars['Int']['input'];
  email: Scalars['String']['input'];
  exitWeight: Scalars['Float']['input'];
  federationNumber?: InputMaybe<Scalars['String']['input']>;
  license?: InputMaybe<Scalars['Int']['input']>;
  name: Scalars['String']['input'];
  phone?: InputMaybe<Scalars['String']['input']>;
  role: Scalars['Int']['input'];
};

/** Autogenerated input type of GrantPermission */
export type GrantPermissionInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzoneUser?: InputMaybe<Scalars['ID']['input']>;
  permission: Permission;
};

/** Autogenerated return type of GrantPermission. */
export type GrantPermissionPayload = {
  __typename?: 'GrantPermissionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of JoinDropzone */
export type JoinDropzoneInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzone: Scalars['ID']['input'];
};

/** Autogenerated return type of JoinDropzone. */
export type JoinDropzonePayload = {
  __typename?: 'JoinDropzonePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of JoinFederation */
export type JoinFederationInput = {
  attributes: UserFederationInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of JoinFederation. */
export type JoinFederationPayload = {
  __typename?: 'JoinFederationPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  userFederation?: Maybe<UserFederation>;
};

export type JumpType = {
  __typename?: 'JumpType';
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type License = AnyResource & {
  __typename?: 'License';
  createdAt: Scalars['ISO8601DateTime']['output'];
  federation?: Maybe<Federation>;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type Load = AnyResource & {
  __typename?: 'Load';
  availableSlots: Scalars['Int']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  dispatchAt?: Maybe<Scalars['Int']['output']>;
  gca?: Maybe<DropzoneUser>;
  guid: Scalars['ID']['output'];
  hasLanded?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  isFull: Scalars['Boolean']['output'];
  isOpen: Scalars['Boolean']['output'];
  isReady: Scalars['Boolean']['output'];
  loadMaster?: Maybe<DropzoneUser>;
  loadNumber: Scalars['Int']['output'];
  maxSlots: Scalars['Int']['output'];
  name?: Maybe<Scalars['String']['output']>;
  occupiedSlots: Scalars['Int']['output'];
  pilot?: Maybe<DropzoneUser>;
  plane: Plane;
  slots?: Maybe<Array<Slot>>;
  state: LoadState;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  weight: Scalars['Int']['output'];
};

/** The connection type for Load. */
export type LoadConnection = {
  __typename?: 'LoadConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<LoadEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Load>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** Autogenerated return type of LoadCreated. */
export type LoadCreatedPayload = {
  __typename?: 'LoadCreatedPayload';
  load?: Maybe<Load>;
};

/** An edge in a connection. */
export type LoadEdge = {
  __typename?: 'LoadEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Load>;
};

export type LoadInput = {
  dispatchAt?: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  gca?: InputMaybe<Scalars['ID']['input']>;
  loadMaster?: InputMaybe<Scalars['ID']['input']>;
  maxSlots?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  pilot?: InputMaybe<Scalars['ID']['input']>;
  plane?: InputMaybe<Scalars['ID']['input']>;
  state?: InputMaybe<LoadState>;
};

export enum LoadState {
  /** boarding_call */
  BoardingCall = 'boarding_call',
  /** cancelled */
  Cancelled = 'cancelled',
  /** in_flight */
  InFlight = 'in_flight',
  /** landed */
  Landed = 'landed',
  /** open */
  Open = 'open'
}

/** Autogenerated return type of LoadUpdated. */
export type LoadUpdatedPayload = {
  __typename?: 'LoadUpdatedPayload';
  load?: Maybe<Load>;
};

export type MasterLog = {
  __typename?: 'MasterLog';
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone?: Maybe<Dropzone>;
  dzso?: Maybe<Array<DropzoneUser>>;
  id: Scalars['ID']['output'];
  loads?: Maybe<Array<Load>>;
  notes?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type MasterLogAircraft = {
  __typename?: 'MasterLogAircraft';
  id?: Maybe<Scalars['ID']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  registration?: Maybe<Scalars['String']['output']>;
};

export type MasterLogEntry = {
  __typename?: 'MasterLogEntry';
  date?: Maybe<Scalars['ISO8601Date']['output']>;
  downloadUrl?: Maybe<Scalars['String']['output']>;
  dzso?: Maybe<MasterLogUser>;
  id: Scalars['ID']['output'];
  loads?: Maybe<Array<MasterLogLoad>>;
  location?: Maybe<GeocodedLocation>;
  notes?: Maybe<Scalars['String']['output']>;
};

export type MasterLogInput = {
  dzso?: InputMaybe<Scalars['ID']['input']>;
  notes?: InputMaybe<Scalars['String']['input']>;
};

export type MasterLogLoad = {
  __typename?: 'MasterLogLoad';
  aircraft?: Maybe<MasterLogAircraft>;
  dispatchAt?: Maybe<Scalars['ISO8601DateTime']['output']>;
  gca?: Maybe<MasterLogUser>;
  id: Scalars['ID']['output'];
  loadMaster?: Maybe<MasterLogUser>;
  loadNumber?: Maybe<Scalars['Int']['output']>;
  pilot?: Maybe<MasterLogUser>;
  slots?: Maybe<Array<MasterLogSlot>>;
};

export type MasterLogSlot = {
  __typename?: 'MasterLogSlot';
  altitude?: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  jumpType?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
};

export type MasterLogUser = {
  __typename?: 'MasterLogUser';
  email?: Maybe<Scalars['String']['output']>;
  id?: Maybe<Scalars['ID']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  nickname?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
};

export enum ModerationRole {
  /** administrator */
  Administrator = 'administrator',
  /** moderator */
  Moderator = 'moderator',
  /** support */
  Support = 'support',
  /** user */
  User = 'user'
}

/** Autogenerated input type of MoveSlot */
export type MoveSlotInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  sourceSlot: Scalars['Int']['input'];
  targetLoad: Scalars['Int']['input'];
  targetSlot?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of MoveSlot. */
export type MoveSlotPayload = {
  __typename?: 'MoveSlotPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  loads?: Maybe<Array<Load>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  archiveRig?: Maybe<DeleteRigPayload>;
  archiveTicketType?: Maybe<DeleteTicketPayload>;
  createDropzone?: Maybe<CreateDropzonePayload>;
  createExtra?: Maybe<CreateExtraPayload>;
  createGhost?: Maybe<CreateGhostPayload>;
  createLoad?: Maybe<CreateLoadPayload>;
  createOrder?: Maybe<CreateOrderPayload>;
  createPlane?: Maybe<CreatePlanePayload>;
  createRig?: Maybe<CreateRigPayload>;
  createRigInspection?: Maybe<CreateRigInspectionPayload>;
  createSlot?: Maybe<CreateSlotPayload>;
  createSlots?: Maybe<CreateSlotsPayload>;
  createTicketType?: Maybe<CreateTicketPayload>;
  createWeatherCondition?: Maybe<CreateWeatherConditionPayload>;
  deleteDropzone?: Maybe<DeleteDropzonePayload>;
  deleteLoad?: Maybe<DeleteLoadPayload>;
  deletePlane?: Maybe<DeletePlanePayload>;
  deleteSlot?: Maybe<DeleteSlotPayload>;
  deleteUser?: Maybe<DeleteUserPayload>;
  finalizeLoad?: Maybe<FinalizeLoadPayload>;
  grantPermission?: Maybe<GrantPermissionPayload>;
  /** Become a member of a public dropzone. Joining a dropzone you already belong to returns your membership. */
  joinDropzone?: Maybe<JoinDropzonePayload>;
  joinFederation?: Maybe<JoinFederationPayload>;
  loginWithApple?: Maybe<ApplePayload>;
  loginWithFacebook?: Maybe<FacebookPayload>;
  moveSlot?: Maybe<MoveSlotPayload>;
  reloadWeatherCondition?: Maybe<ReloadWeatherConditionPayload>;
  revokePermission?: Maybe<RevokePermissionPayload>;
  updateDropzone?: Maybe<UpdateDropzonePayload>;
  updateDropzoneUser?: Maybe<UpdateDropzoneUserPayload>;
  updateExtra?: Maybe<UpdateExtraPayload>;
  updateFormTemplate?: Maybe<UpdateFormTemplatePayload>;
  updateLoad?: Maybe<UpdateLoadPayload>;
  updateMasterLog?: Maybe<UpdateMasterLogPayload>;
  updateNotification?: Maybe<UpdateNotificationPayload>;
  updatePlane?: Maybe<UpdatePlanePayload>;
  updateRig?: Maybe<UpdateRigPayload>;
  updateRigInspection?: Maybe<UpdateRigInspectionPayload>;
  updateRole?: Maybe<UpdateRolePayload>;
  updateSlot?: Maybe<UpdateSlotPayload>;
  updateTicketType?: Maybe<UpdateTicketPayload>;
  updateUser?: Maybe<UpdateUserPayload>;
  updateVisibility?: Maybe<UpdateVisibilityPayload>;
  userConfirmRegistrationWithToken?: Maybe<UserConfirmRegistrationWithTokenPayload>;
  userLogin?: Maybe<UserLoginPayload>;
  userLogout?: Maybe<UserLogoutPayload>;
  userRegister?: Maybe<SignUpPayload>;
  userResendConfirmationWithToken?: Maybe<UserResendConfirmationWithTokenPayload>;
  userSendPasswordResetWithToken?: Maybe<UserSendPasswordResetWithTokenPayload>;
  userUpdatePasswordWithToken?: Maybe<UserUpdatePasswordWithTokenPayload>;
};


export type MutationArchiveRigArgs = {
  input: DeleteRigInput;
};


export type MutationArchiveTicketTypeArgs = {
  input: DeleteTicketInput;
};


export type MutationCreateDropzoneArgs = {
  input: CreateDropzoneInput;
};


export type MutationCreateExtraArgs = {
  input: CreateExtraInput;
};


export type MutationCreateGhostArgs = {
  input: CreateGhostInput;
};


export type MutationCreateLoadArgs = {
  input: CreateLoadInput;
};


export type MutationCreateOrderArgs = {
  input: CreateOrderInput;
};


export type MutationCreatePlaneArgs = {
  input: CreatePlaneInput;
};


export type MutationCreateRigArgs = {
  input: CreateRigInput;
};


export type MutationCreateRigInspectionArgs = {
  input: CreateRigInspectionInput;
};


export type MutationCreateSlotArgs = {
  input: CreateSlotInput;
};


export type MutationCreateSlotsArgs = {
  input: CreateSlotsInput;
};


export type MutationCreateTicketTypeArgs = {
  input: CreateTicketInput;
};


export type MutationCreateWeatherConditionArgs = {
  input: CreateWeatherConditionInput;
};


export type MutationDeleteDropzoneArgs = {
  input: DeleteDropzoneInput;
};


export type MutationDeleteLoadArgs = {
  input: DeleteLoadInput;
};


export type MutationDeletePlaneArgs = {
  input: DeletePlaneInput;
};


export type MutationDeleteSlotArgs = {
  input: DeleteSlotInput;
};


export type MutationDeleteUserArgs = {
  input: DeleteUserInput;
};


export type MutationFinalizeLoadArgs = {
  input: FinalizeLoadInput;
};


export type MutationGrantPermissionArgs = {
  input: GrantPermissionInput;
};


export type MutationJoinDropzoneArgs = {
  input: JoinDropzoneInput;
};


export type MutationJoinFederationArgs = {
  input: JoinFederationInput;
};


export type MutationLoginWithAppleArgs = {
  confirmUrl?: InputMaybe<Scalars['String']['input']>;
  pushToken?: InputMaybe<Scalars['String']['input']>;
  token: Scalars['String']['input'];
  userIdentity: Scalars['String']['input'];
};


export type MutationLoginWithFacebookArgs = {
  confirmUrl?: InputMaybe<Scalars['String']['input']>;
  pushToken?: InputMaybe<Scalars['String']['input']>;
  token: Scalars['String']['input'];
};


export type MutationMoveSlotArgs = {
  input: MoveSlotInput;
};


export type MutationReloadWeatherConditionArgs = {
  input: ReloadWeatherConditionInput;
};


export type MutationRevokePermissionArgs = {
  input: RevokePermissionInput;
};


export type MutationUpdateDropzoneArgs = {
  input: UpdateDropzoneInput;
};


export type MutationUpdateDropzoneUserArgs = {
  input: UpdateDropzoneUserInput;
};


export type MutationUpdateExtraArgs = {
  input: UpdateExtraInput;
};


export type MutationUpdateFormTemplateArgs = {
  input: UpdateFormTemplateInput;
};


export type MutationUpdateLoadArgs = {
  input: UpdateLoadInput;
};


export type MutationUpdateMasterLogArgs = {
  input: UpdateMasterLogInput;
};


export type MutationUpdateNotificationArgs = {
  input: UpdateNotificationInput;
};


export type MutationUpdatePlaneArgs = {
  input: UpdatePlaneInput;
};


export type MutationUpdateRigArgs = {
  input: UpdateRigInput;
};


export type MutationUpdateRigInspectionArgs = {
  input: UpdateRigInspectionInput;
};


export type MutationUpdateRoleArgs = {
  input: UpdateRoleInput;
};


export type MutationUpdateSlotArgs = {
  input: UpdateSlotInput;
};


export type MutationUpdateTicketTypeArgs = {
  input: UpdateTicketInput;
};


export type MutationUpdateUserArgs = {
  input: UpdateUserInput;
};


export type MutationUpdateVisibilityArgs = {
  input: UpdateVisibilityInput;
};


export type MutationUserConfirmRegistrationWithTokenArgs = {
  confirmationToken: Scalars['String']['input'];
};


export type MutationUserLoginArgs = {
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
};


export type MutationUserRegisterArgs = {
  confirmUrl?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
  exitWeight: Scalars['Float']['input'];
  licenseId?: InputMaybe<Scalars['Int']['input']>;
  name: Scalars['String']['input'];
  password: Scalars['String']['input'];
  passwordConfirmation: Scalars['String']['input'];
  phone: Scalars['String']['input'];
  pushToken?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUserResendConfirmationWithTokenArgs = {
  confirmUrl: Scalars['String']['input'];
  email: Scalars['String']['input'];
};


export type MutationUserSendPasswordResetWithTokenArgs = {
  email: Scalars['String']['input'];
  redirectUrl: Scalars['String']['input'];
};


export type MutationUserUpdatePasswordWithTokenArgs = {
  password: Scalars['String']['input'];
  passwordConfirmation: Scalars['String']['input'];
  resetPasswordToken: Scalars['String']['input'];
};

export type Notification = {
  __typename?: 'Notification';
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  isSeen: Scalars['Boolean']['output'];
  message?: Maybe<Scalars['String']['output']>;
  notificationType?: Maybe<NotificationType>;
  receivedBy: DropzoneUser;
  resource?: Maybe<AnyResource>;
  sentBy?: Maybe<DropzoneUser>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The connection type for Notification. */
export type NotificationConnection = {
  __typename?: 'NotificationConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<NotificationEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Notification>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type NotificationEdge = {
  __typename?: 'NotificationEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Notification>;
};

export type NotificationInput = {
  isSeen: Scalars['Boolean']['input'];
};

export enum NotificationType {
  /** boarding_call */
  BoardingCall = 'boarding_call',
  /** boarding_call_canceled */
  BoardingCallCanceled = 'boarding_call_canceled',
  /** credits_updated */
  CreditsUpdated = 'credits_updated',
  /** membership_updated */
  MembershipUpdated = 'membership_updated',
  /** packjob_confirmed */
  PackjobConfirmed = 'packjob_confirmed',
  /** packjob_pending_confirm */
  PackjobPendingConfirm = 'packjob_pending_confirm',
  /** permission_granted */
  PermissionGranted = 'permission_granted',
  /** permission_revoked */
  PermissionRevoked = 'permission_revoked',
  /** publication_requested */
  PublicationRequested = 'publication_requested',
  /** rig_inspection_completed */
  RigInspectionCompleted = 'rig_inspection_completed',
  /** rig_inspection_requested */
  RigInspectionRequested = 'rig_inspection_requested',
  /** rig_pending_inspection */
  RigPendingInspection = 'rig_pending_inspection',
  /** system */
  System = 'system',
  /** user_manifested */
  UserManifested = 'user_manifested'
}

export type Order = AnyResource & {
  __typename?: 'Order';
  amount: Scalars['Float']['output'];
  buyer?: Maybe<Wallet>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone: Dropzone;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  item?: Maybe<SellableItem>;
  orderNumber: Scalars['Int']['output'];
  receipts?: Maybe<Array<Receipt>>;
  seller?: Maybe<Wallet>;
  state: OrderState;
  title?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** The connection type for Order. */
export type OrderConnection = {
  __typename?: 'OrderConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<OrderEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Order>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type OrderEdge = {
  __typename?: 'OrderEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Order>;
};

export type OrderInput = {
  /** Total amount of the order */
  amount: Scalars['Float']['input'];
  /** Any buyer peer, e.g DropzoneUser or Dropzone */
  buyer: Scalars['ID']['input'];
  dropzone: Scalars['ID']['input'];
  /** Item to attach to order */
  sellableItem?: InputMaybe<Scalars['ID']['input']>;
  /** Any sales peer, e.g DropzoneUser or Dropzone */
  seller: Scalars['ID']['input'];
  title?: InputMaybe<Scalars['String']['input']>;
};

export enum OrderState {
  /** cancelled */
  Cancelled = 'cancelled',
  /** completed */
  Completed = 'completed',
  /** pending */
  Pending = 'pending',
  /** refunded */
  Refunded = 'refunded'
}

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']['output']>;
};

export enum Permission {
  ActAsDzso = 'actAsDZSO',
  ActAsGca = 'actAsGCA',
  ActAsLoadMaster = 'actAsLoadMaster',
  ActAsPilot = 'actAsPilot',
  ActAsRigInspector = 'actAsRigInspector',
  CreateDoubleSlot = 'createDoubleSlot',
  CreateDropzoneRig = 'createDropzoneRig',
  CreateExtra = 'createExtra',
  CreateFormTemplate = 'createFormTemplate',
  CreateLoad = 'createLoad',
  CreatePackjob = 'createPackjob',
  CreatePlane = 'createPlane',
  CreateRig = 'createRig',
  CreateSlot = 'createSlot',
  CreateStudentSlot = 'createStudentSlot',
  CreateTicketType = 'createTicketType',
  CreateUser = 'createUser',
  CreateUserDoubleSlot = 'createUserDoubleSlot',
  CreateUserSlot = 'createUserSlot',
  CreateUserSlotWithSelf = 'createUserSlotWithSelf',
  CreateUserTransaction = 'createUserTransaction',
  DeleteDropzone = 'deleteDropzone',
  DeleteDropzoneRig = 'deleteDropzoneRig',
  DeleteExtra = 'deleteExtra',
  DeleteFormTemplate = 'deleteFormTemplate',
  DeleteLoad = 'deleteLoad',
  DeletePackjob = 'deletePackjob',
  DeletePlane = 'deletePlane',
  DeleteRig = 'deleteRig',
  DeleteSlot = 'deleteSlot',
  DeleteStudentSlot = 'deleteStudentSlot',
  DeleteTicketType = 'deleteTicketType',
  DeleteUser = 'deleteUser',
  DeleteUserSlot = 'deleteUserSlot',
  GrantPermission = 'grantPermission',
  ReadDropzoneRig = 'readDropzoneRig',
  ReadExtra = 'readExtra',
  ReadFormTemplate = 'readFormTemplate',
  ReadLoad = 'readLoad',
  ReadPackjob = 'readPackjob',
  ReadPermissions = 'readPermissions',
  ReadRig = 'readRig',
  ReadUser = 'readUser',
  ReadUserTransactions = 'readUserTransactions',
  RevokePermission = 'revokePermission',
  UndeleteDropzone = 'undeleteDropzone',
  UndeleteDropzoneRig = 'undeleteDropzoneRig',
  UndeleteExtra = 'undeleteExtra',
  UndeletePlane = 'undeletePlane',
  UndeleteRig = 'undeleteRig',
  UndeleteStudentSlot = 'undeleteStudentSlot',
  UndeleteTicketType = 'undeleteTicketType',
  UndeleteUser = 'undeleteUser',
  UndeleteUserSlot = 'undeleteUserSlot',
  UpdateDropzone = 'updateDropzone',
  UpdateDropzoneRig = 'updateDropzoneRig',
  UpdateExtra = 'updateExtra',
  UpdateFormTemplate = 'updateFormTemplate',
  UpdateLoad = 'updateLoad',
  UpdatePackjob = 'updatePackjob',
  UpdatePermissions = 'updatePermissions',
  UpdatePlane = 'updatePlane',
  UpdateRig = 'updateRig',
  UpdateSlot = 'updateSlot',
  UpdateStudentSlot = 'updateStudentSlot',
  UpdateTicketType = 'updateTicketType',
  UpdateUser = 'updateUser',
  UpdateUserSlot = 'updateUserSlot',
  UpdateWeatherConditions = 'updateWeatherConditions',
  ViewAdminActivity = 'viewAdminActivity',
  ViewRevenue = 'viewRevenue',
  ViewStatistics = 'viewStatistics',
  ViewSystemActivity = 'viewSystemActivity',
  ViewUserActivity = 'viewUserActivity'
}

export type Plane = AnyResource & {
  __typename?: 'Plane';
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone: Dropzone;
  guid: Scalars['ID']['output'];
  hours?: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  maxSlots: Scalars['Int']['output'];
  minSlots?: Maybe<Scalars['Int']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  nextMaintenanceHours?: Maybe<Scalars['Int']['output']>;
  registration?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type PlaneInput = {
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  hours?: InputMaybe<Scalars['Int']['input']>;
  maxSlots?: InputMaybe<Scalars['Int']['input']>;
  minSlots?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  nextMaintenanceHours?: InputMaybe<Scalars['Int']['input']>;
  registration?: InputMaybe<Scalars['String']['input']>;
};

export type Query = {
  __typename?: 'Query';
  /** Get all Activity Events for a dropzone (or all dropzones) */
  activity: EventConnection;
  /** Get user rigs that have been inspected and marked as OK + dropzone rigs */
  availableRigs?: Maybe<Array<Rig>>;
  /** Currently authenticated user */
  currentUser?: Maybe<User>;
  /** Get dropzone details */
  dropzone?: Maybe<Dropzone>;
  /** Get a specific user at a dropzone */
  dropzoneUser?: Maybe<DropzoneUser>;
  /** Search users at a dropzone */
  dropzoneUsers?: Maybe<DropzoneUserConnection>;
  /** Get all available dropzones */
  dropzones: DropzoneConnection;
  /** Get all ticket type extras */
  extras: Array<Extra>;
  /** Get all available federations */
  federations: Array<Federation>;
  /** Find location by searching */
  geocode?: Maybe<GeocodedLocation>;
  /** Get all jump types */
  jumpTypes: Array<JumpType>;
  /** Get all licenses for a federation */
  licenses: Array<License>;
  /** Get load by id */
  load?: Maybe<Load>;
  /** Get all loads */
  loads: LoadConnection;
  /** Get the master log entry for a specific day */
  masterLog?: Maybe<MasterLogEntry>;
  /** Get Aircrafts for a dropzone */
  planes?: Maybe<Array<Plane>>;
  /** Get ticket types for a dropzone */
  ticketTypes?: Maybe<Array<TicketType>>;
};


export type QueryActivityArgs = {
  accessLevels?: InputMaybe<Array<EventAccessLevel>>;
  actions?: InputMaybe<Array<EventAction>>;
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  createdBy?: InputMaybe<Array<Scalars['ID']['input']>>;
  dropzone?: InputMaybe<Array<Scalars['ID']['input']>>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  levels?: InputMaybe<Array<EventLevel>>;
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type QueryAvailableRigsArgs = {
  dropzoneUser: Scalars['Int']['input'];
  isTandem?: InputMaybe<Scalars['Boolean']['input']>;
  loadId?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryDropzoneArgs = {
  id: Scalars['ID']['input'];
};


export type QueryDropzoneUserArgs = {
  id: Scalars['ID']['input'];
};


export type QueryDropzoneUsersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  dropzone: Scalars['ID']['input'];
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  licensed?: InputMaybe<Scalars['Boolean']['input']>;
  permissions?: InputMaybe<Array<Permission>>;
  search?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDropzonesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  state?: InputMaybe<Array<DropzoneState>>;
};


export type QueryExtrasArgs = {
  dropzone?: InputMaybe<Scalars['ID']['input']>;
  ticketType?: InputMaybe<Scalars['ID']['input']>;
};


export type QueryGeocodeArgs = {
  search: Scalars['String']['input'];
};


export type QueryJumpTypesArgs = {
  dropzoneUsers?: InputMaybe<Array<Scalars['Int']['input']>>;
};


export type QueryLicensesArgs = {
  federationId?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryLoadArgs = {
  id: Scalars['ID']['input'];
};


export type QueryLoadsArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['ISO8601Date']['input']>;
  dropzone: Scalars['ID']['input'];
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMasterLogArgs = {
  date: Scalars['ISO8601Date']['input'];
  dropzone: Scalars['ID']['input'];
};


export type QueryPlanesArgs = {
  dropzone: Scalars['ID']['input'];
};


export type QueryTicketTypesArgs = {
  allowManifestingSelf?: InputMaybe<Scalars['Boolean']['input']>;
  dropzone: Scalars['ID']['input'];
};

export type Receipt = AnyResource & {
  __typename?: 'Receipt';
  amountCents?: Maybe<Scalars['Int']['output']>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  order: Order;
  transactions: Array<Transaction>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated input type of ReloadWeatherCondition */
export type ReloadWeatherConditionInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of ReloadWeatherCondition. */
export type ReloadWeatherConditionPayload = {
  __typename?: 'ReloadWeatherConditionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  weatherCondition?: Maybe<WeatherCondition>;
};

/** Autogenerated input type of RevokePermission */
export type RevokePermissionInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzoneUser?: InputMaybe<Scalars['ID']['input']>;
  permission: Permission;
};

/** Autogenerated return type of RevokePermission. */
export type RevokePermissionPayload = {
  __typename?: 'RevokePermissionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

export type Rig = AnyResource & {
  __typename?: 'Rig';
  canopySize?: Maybe<Scalars['Int']['output']>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone?: Maybe<Dropzone>;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  isPublic: Scalars['Boolean']['output'];
  maintainedAt?: Maybe<Scalars['Int']['output']>;
  make?: Maybe<Scalars['String']['output']>;
  model?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  owner?: Maybe<User>;
  packValue?: Maybe<Scalars['Int']['output']>;
  packingCard?: Maybe<Scalars['String']['output']>;
  repackExpiresAt?: Maybe<Scalars['Int']['output']>;
  rigInspections?: Maybe<RigInspection>;
  rigType?: Maybe<Scalars['String']['output']>;
  serial?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};


export type RigRigInspectionsArgs = {
  dropzoneId: Scalars['ID']['input'];
};

export type RigInput = {
  canopySize?: InputMaybe<Scalars['Int']['input']>;
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  isPublic?: InputMaybe<Scalars['Boolean']['input']>;
  maintainedAt?: InputMaybe<Scalars['Int']['input']>;
  make?: InputMaybe<Scalars['String']['input']>;
  model?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  packValue?: InputMaybe<Scalars['Int']['input']>;
  packingCard?: InputMaybe<Scalars['String']['input']>;
  repackExpiresAt?: InputMaybe<Scalars['Int']['input']>;
  /** student / sport / tandem */
  rigType?: InputMaybe<Scalars['String']['input']>;
  serial?: InputMaybe<Scalars['String']['input']>;
  userId?: InputMaybe<Scalars['Int']['input']>;
};

export type RigInspection = AnyResource & {
  __typename?: 'RigInspection';
  createdAt: Scalars['ISO8601DateTime']['output'];
  definition: Scalars['String']['output'];
  dropzoneUser: DropzoneUser;
  formTemplate: FormTemplate;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  inspectedBy: DropzoneUser;
  isOk: Scalars['Boolean']['output'];
  rig?: Maybe<Rig>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type RigInspectionInput = {
  definition?: InputMaybe<Scalars['String']['input']>;
  dropzone?: InputMaybe<Scalars['ID']['input']>;
  isOk?: InputMaybe<Scalars['Boolean']['input']>;
  rig?: InputMaybe<Scalars['ID']['input']>;
};

export type SellableItem = {
  cost?: Maybe<Scalars['Float']['output']>;
  title?: Maybe<Scalars['String']['output']>;
};

export type Settings = {
  __typename?: 'Settings';
  /** Allow users to double-manifest */
  allowDoubleManifesting?: Maybe<Scalars['Boolean']['output']>;
  /** Allow manifest to bypass all rules? */
  allowManifestBypass?: Maybe<Scalars['Boolean']['output']>;
  /** When this is enabled, users can manifest even if they go into negatives */
  allowNegativeCredits?: Maybe<Scalars['Boolean']['output']>;
  /** When this is enabled, users cannot manifest if they have no credits */
  requireCredits?: Maybe<Scalars['Boolean']['output']>;
  /** When this is enabled, users cannot manifest if they have no equipment */
  requireEquipment?: Maybe<Scalars['Boolean']['output']>;
  /** Should a valid license be required to manifest a jump? */
  requireLicense?: Maybe<Scalars['Boolean']['output']>;
  /** When this is enabled, users cannot manifest if their membership is out of date */
  requireMembership?: Maybe<Scalars['Boolean']['output']>;
  /** When this is enabled, users cannot manifest if their reserve is out of date */
  requireReserveInDate?: Maybe<Scalars['Boolean']['output']>;
  /** Whether or not rig inspections are required before manifesting a jump */
  requireRigInspection?: Maybe<Scalars['Boolean']['output']>;
};

export type SettingsInput = {
  /** Allow users to double-manifest */
  allowDoubleManifesting?: InputMaybe<Scalars['Boolean']['input']>;
  /** Allow manifest to bypass all rules? */
  allowManifestBypass?: InputMaybe<Scalars['Boolean']['input']>;
  /** When this is enabled, users can manifest even if they go into negatives */
  allowNegativeCredits?: InputMaybe<Scalars['Boolean']['input']>;
  /** When this is enabled, users cannot manifest if they have no credits */
  requireCredits?: InputMaybe<Scalars['Boolean']['input']>;
  /** When this is enabled, users cannot manifest if they have no equipment */
  requireEquipment?: InputMaybe<Scalars['Boolean']['input']>;
  /** Should a valid license be required to manifest a jump? */
  requireLicense?: InputMaybe<Scalars['Boolean']['input']>;
  /** When this is enabled, users cannot manifest if their membership is out of date */
  requireMembership?: InputMaybe<Scalars['Boolean']['input']>;
  /** When this is enabled, users cannot manifest if their reserve is out of date */
  requireReserveInDate?: InputMaybe<Scalars['Boolean']['input']>;
  /** Whether or not rig inspections are required before manifesting a jump */
  requireRigInspection?: InputMaybe<Scalars['Boolean']['input']>;
};

/** Autogenerated return type of SignUp. */
export type SignUpPayload = {
  __typename?: 'SignUpPayload';
  authenticatable?: Maybe<User>;
  /**
   * Authentication credentials. Null if after signUp resource is not active for
   * authentication (e.g. Email confirmation required).
   */
  credentials?: Maybe<Credential>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

export type Slot = AnyResource & SellableItem & {
  __typename?: 'Slot';
  cost: Scalars['Float']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzoneUser?: Maybe<DropzoneUser>;
  exitWeight: Scalars['Int']['output'];
  extras?: Maybe<Array<Extra>>;
  groupNumber: Scalars['Int']['output'];
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  jumpType?: Maybe<JumpType>;
  load: Load;
  order?: Maybe<Order>;
  passengerExitWeight?: Maybe<Scalars['Float']['output']>;
  passengerName?: Maybe<Scalars['String']['output']>;
  rig?: Maybe<Rig>;
  ticketType?: Maybe<TicketType>;
  title?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  wingLoading?: Maybe<Scalars['Float']['output']>;
};

/** The connection type for Slot. */
export type SlotConnection = {
  __typename?: 'SlotConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<SlotEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Slot>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type SlotEdge = {
  __typename?: 'SlotEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Slot>;
};

export type SlotInput = {
  dropzoneUser?: InputMaybe<Scalars['ID']['input']>;
  exitWeight?: InputMaybe<Scalars['Float']['input']>;
  extras?: InputMaybe<Array<Scalars['ID']['input']>>;
  groupNumber?: InputMaybe<Scalars['Int']['input']>;
  jumpType?: InputMaybe<Scalars['ID']['input']>;
  load?: InputMaybe<Scalars['ID']['input']>;
  passengerExitWeight?: InputMaybe<Scalars['Float']['input']>;
  passengerName?: InputMaybe<Scalars['String']['input']>;
  rig?: InputMaybe<Scalars['ID']['input']>;
  ticketType?: InputMaybe<Scalars['ID']['input']>;
  userGroup?: InputMaybe<Array<SlotUser>>;
};

export type SlotUser = {
  exitWeight: Scalars['Float']['input'];
  id: Scalars['Int']['input'];
  passengerExitWeight?: InputMaybe<Scalars['Float']['input']>;
  passengerName?: InputMaybe<Scalars['String']['input']>;
  rig?: InputMaybe<Scalars['ID']['input']>;
};

export type Statistics = {
  __typename?: 'Statistics';
  activeUserCount: Scalars['Int']['output'];
  cancelledLoadsCount: Scalars['Int']['output'];
  dzsoCount: Scalars['Int']['output'];
  finalizedLoadsCount: Scalars['Int']['output'];
  gcaCount: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  inactiveUserCount: Scalars['Int']['output'];
  /** Get the number of loads dispatched per day */
  loadCountByDay?: Maybe<Array<StatisticsByDate>>;
  loadsCount: Scalars['Int']['output'];
  pilotCount: Scalars['Int']['output'];
  revenueCentsCount: Scalars['Int']['output'];
  rigInspectorCount: Scalars['Int']['output'];
  /** Get the number of slots by jump type */
  slotsByJumpType?: Maybe<Array<StatisticsByName>>;
  slotsCount: Scalars['Int']['output'];
  totalUserCount: Scalars['Int']['output'];
};


export type StatisticsCancelledLoadsCountArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsFinalizedLoadsCountArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsLoadCountByDayArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsLoadsCountArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsRevenueCentsCountArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsSlotsByJumpTypeArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};


export type StatisticsSlotsCountArgs = {
  timeRange?: InputMaybe<TimeRangeInput>;
};

export type StatisticsByDate = {
  __typename?: 'StatisticsByDate';
  count: Scalars['Int']['output'];
  date: Scalars['ISO8601Date']['output'];
};

export type StatisticsByName = {
  __typename?: 'StatisticsByName';
  count: Scalars['Int']['output'];
  name: Scalars['String']['output'];
};

export type Subscription = {
  __typename?: 'Subscription';
  loadCreated: LoadCreatedPayload;
  loadUpdated: LoadUpdatedPayload;
  userUpdated: UserUpdatedPayload;
};


export type SubscriptionLoadCreatedArgs = {
  dropzoneId: Scalars['ID']['input'];
};


export type SubscriptionLoadUpdatedArgs = {
  loadId: Scalars['ID']['input'];
};


export type SubscriptionUserUpdatedArgs = {
  dropzoneUserId: Scalars['ID']['input'];
};

export type TicketType = AnyResource & SellableItem & {
  __typename?: 'TicketType';
  allowManifestingSelf?: Maybe<Scalars['Boolean']['output']>;
  altitude?: Maybe<Scalars['Int']['output']>;
  cost: Scalars['Float']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  currency?: Maybe<Scalars['String']['output']>;
  dropzone?: Maybe<Dropzone>;
  extras: Array<Extra>;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  isTandem?: Maybe<Scalars['Boolean']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type TicketTypeInput = {
  allowManifestingSelf?: InputMaybe<Scalars['Boolean']['input']>;
  altitude?: InputMaybe<Scalars['Int']['input']>;
  cost?: InputMaybe<Scalars['Float']['input']>;
  currency?: InputMaybe<Scalars['String']['input']>;
  dropzoneId?: InputMaybe<Scalars['Int']['input']>;
  extraIds?: InputMaybe<Array<Scalars['Int']['input']>>;
  isTandem?: InputMaybe<Scalars['Boolean']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type TimeRangeInput = {
  endTime?: InputMaybe<Scalars['ISO8601DateTime']['input']>;
  startTime?: InputMaybe<Scalars['ISO8601DateTime']['input']>;
};

export type Transaction = AnyResource & {
  __typename?: 'Transaction';
  amount: Scalars['Float']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzoneUser: DropzoneUser;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  message?: Maybe<Scalars['String']['output']>;
  receipt: Receipt;
  receiver?: Maybe<Wallet>;
  sender?: Maybe<Wallet>;
  status: TransactionStatus;
  transactionType: TransactionType;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export enum TransactionStatus {
  Cancelled = 'cancelled',
  Completed = 'completed',
  Reserved = 'reserved'
}

export enum TransactionType {
  Deposit = 'deposit',
  Purchase = 'purchase',
  Refund = 'refund',
  Sale = 'sale',
  Withdrawal = 'withdrawal'
}

/** Autogenerated input type of UpdateDropzone */
export type UpdateDropzoneInput = {
  attributes: DropzoneInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of UpdateDropzone. */
export type UpdateDropzonePayload = {
  __typename?: 'UpdateDropzonePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzone?: Maybe<Dropzone>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of UpdateDropzoneUser */
export type UpdateDropzoneUserInput = {
  attributes: DropzoneUserInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzoneUser?: InputMaybe<Scalars['ID']['input']>;
};

/** Autogenerated return type of UpdateDropzoneUser. */
export type UpdateDropzoneUserPayload = {
  __typename?: 'UpdateDropzoneUserPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of UpdateExtra */
export type UpdateExtraInput = {
  attributes: ExtraInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpdateExtra. */
export type UpdateExtraPayload = {
  __typename?: 'UpdateExtraPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  extra?: Maybe<Extra>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of UpdateFormTemplate */
export type UpdateFormTemplateInput = {
  attributes: FormTemplateInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpdateFormTemplate. */
export type UpdateFormTemplatePayload = {
  __typename?: 'UpdateFormTemplatePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  formTemplate?: Maybe<FormTemplate>;
};

/** Autogenerated input type of UpdateLoad */
export type UpdateLoadInput = {
  attributes: LoadInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
};

/** Autogenerated return type of UpdateLoad. */
export type UpdateLoadPayload = {
  __typename?: 'UpdateLoadPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  load?: Maybe<Load>;
};

/** Autogenerated input type of UpdateMasterLog */
export type UpdateMasterLogInput = {
  attributes: MasterLogInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  date: Scalars['ISO8601Date']['input'];
  dropzone: Scalars['ID']['input'];
};

/** Autogenerated return type of UpdateMasterLog. */
export type UpdateMasterLogPayload = {
  __typename?: 'UpdateMasterLogPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  masterLog?: Maybe<MasterLogEntry>;
};

/** Autogenerated input type of UpdateNotification */
export type UpdateNotificationInput = {
  attributes: NotificationInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpdateNotification. */
export type UpdateNotificationPayload = {
  __typename?: 'UpdateNotificationPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  notification?: Maybe<Notification>;
};

/** Autogenerated input type of UpdatePlane */
export type UpdatePlaneInput = {
  attributes: PlaneInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of UpdatePlane. */
export type UpdatePlanePayload = {
  __typename?: 'UpdatePlanePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  plane?: Maybe<Plane>;
};

/** Autogenerated input type of UpdateRig */
export type UpdateRigInput = {
  attributes: RigInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated input type of UpdateRigInspection */
export type UpdateRigInspectionInput = {
  attributes: RigInspectionInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated return type of UpdateRigInspection. */
export type UpdateRigInspectionPayload = {
  __typename?: 'UpdateRigInspectionPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  rigInspection?: Maybe<RigInspection>;
};

/** Autogenerated return type of UpdateRig. */
export type UpdateRigPayload = {
  __typename?: 'UpdateRigPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  rig?: Maybe<Rig>;
};

/** Autogenerated input type of UpdateRole */
export type UpdateRoleInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  enabled: Scalars['Boolean']['input'];
  id?: InputMaybe<Scalars['Int']['input']>;
  permission: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRole. */
export type UpdateRolePayload = {
  __typename?: 'UpdateRolePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  role?: Maybe<UserRole>;
};

/** Autogenerated input type of UpdateSlot */
export type UpdateSlotInput = {
  attributes: SlotInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of UpdateSlot. */
export type UpdateSlotPayload = {
  __typename?: 'UpdateSlotPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  slot?: Maybe<Slot>;
};

/** Autogenerated input type of UpdateTicket */
export type UpdateTicketInput = {
  attributes: TicketTypeInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['Int']['input'];
};

/** Autogenerated return type of UpdateTicket. */
export type UpdateTicketPayload = {
  __typename?: 'UpdateTicketPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
  ticketType?: Maybe<TicketType>;
};

/** Autogenerated input type of UpdateUser */
export type UpdateUserInput = {
  attributes: UserInput;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzoneUser?: InputMaybe<Scalars['ID']['input']>;
};

/** Autogenerated return type of UpdateUser. */
export type UpdateUserPayload = {
  __typename?: 'UpdateUserPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzoneUser?: Maybe<DropzoneUser>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

/** Autogenerated input type of UpdateVisibility */
export type UpdateVisibilityInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  dropzone: Scalars['ID']['input'];
  event: DropzoneStateEvent;
};

/** Autogenerated return type of UpdateVisibility. */
export type UpdateVisibilityPayload = {
  __typename?: 'UpdateVisibilityPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  dropzone?: Maybe<Dropzone>;
  errors?: Maybe<Array<Scalars['String']['output']>>;
  fieldErrors?: Maybe<Array<FieldError>>;
};

export type User = AnyResource & {
  __typename?: 'User';
  apfNumber?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzoneUsers?: Maybe<Array<DropzoneUser>>;
  email?: Maybe<Scalars['String']['output']>;
  exitWeight?: Maybe<Scalars['String']['output']>;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  image?: Maybe<Scalars['String']['output']>;
  licenses?: Maybe<Array<License>>;
  moderationRole?: Maybe<ModerationRole>;
  name?: Maybe<Scalars['String']['output']>;
  nickname?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  pushToken?: Maybe<Scalars['String']['output']>;
  rigs?: Maybe<Array<Rig>>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  userFederations?: Maybe<Array<UserFederation>>;
};

/** Autogenerated return type of UserConfirmRegistrationWithToken. */
export type UserConfirmRegistrationWithTokenPayload = {
  __typename?: 'UserConfirmRegistrationWithTokenPayload';
  authenticatable: User;
  /** Authentication credentials. Null unless user is signed in after confirmation. */
  credentials?: Maybe<Credential>;
};

export type UserFederation = AnyResource & {
  __typename?: 'UserFederation';
  federation: Federation;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  license?: Maybe<License>;
  qualifications?: Maybe<Array<UserQualification>>;
  /** User Federation ID, e.g APF number */
  uid?: Maybe<Scalars['String']['output']>;
  user: User;
};

export type UserFederationInput = {
  federation: Scalars['ID']['input'];
  license?: InputMaybe<Scalars['ID']['input']>;
  /** User Federation ID, e.g APF number */
  uid?: InputMaybe<Scalars['String']['input']>;
};

export type UserInput = {
  email?: InputMaybe<Scalars['String']['input']>;
  exitWeight?: InputMaybe<Scalars['Float']['input']>;
  federationNumber?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  license?: InputMaybe<Scalars['Int']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  nickname?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  pushToken?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UserLogin. */
export type UserLoginPayload = {
  __typename?: 'UserLoginPayload';
  authenticatable: User;
  credentials: Credential;
};

/** Autogenerated return type of UserLogout. */
export type UserLogoutPayload = {
  __typename?: 'UserLogoutPayload';
  authenticatable: User;
};

export type UserQualification = AnyResource & {
  __typename?: 'UserQualification';
  expiresAt?: Maybe<Scalars['Int']['output']>;
  guid: Scalars['ID']['output'];
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  uid?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated return type of UserResendConfirmationWithToken. */
export type UserResendConfirmationWithTokenPayload = {
  __typename?: 'UserResendConfirmationWithTokenPayload';
  message: Scalars['String']['output'];
};

export type UserRole = {
  __typename?: 'UserRole';
  createdAt: Scalars['ISO8601DateTime']['output'];
  dropzone: Dropzone;
  dropzoneId: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  name?: Maybe<Scalars['String']['output']>;
  permissions: Array<Scalars['String']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated return type of UserSendPasswordResetWithToken. */
export type UserSendPasswordResetWithTokenPayload = {
  __typename?: 'UserSendPasswordResetWithTokenPayload';
  message: Scalars['String']['output'];
};

/** Autogenerated return type of UserUpdatePasswordWithToken. */
export type UserUpdatePasswordWithTokenPayload = {
  __typename?: 'UserUpdatePasswordWithTokenPayload';
  authenticatable: User;
  /** Authentication credentials. Resource must be signed_in for credentials to be returned. */
  credentials?: Maybe<Credential>;
};

/** Autogenerated return type of UserUpdated. */
export type UserUpdatedPayload = {
  __typename?: 'UserUpdatedPayload';
  dropzoneUser?: Maybe<DropzoneUser>;
};

export type Wallet = {
  orders?: Maybe<OrderConnection>;
  purchases?: Maybe<OrderConnection>;
  sales?: Maybe<OrderConnection>;
  walletId: Scalars['ID']['output'];
};


export type WalletOrdersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  startDate?: InputMaybe<Scalars['Int']['input']>;
};


export type WalletPurchasesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type WalletSalesArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
};

export type WeatherCondition = {
  __typename?: 'WeatherCondition';
  createdAt: Scalars['ISO8601DateTime']['output'];
  exitSpotMiles?: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  jumpRun?: Maybe<Scalars['Int']['output']>;
  offsetDirection?: Maybe<Scalars['Int']['output']>;
  offsetMiles?: Maybe<Scalars['Int']['output']>;
  temperature?: Maybe<Scalars['Int']['output']>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  winds?: Maybe<Array<Wind>>;
};

export type WeatherConditionInput = {
  dropzoneId: Scalars['Int']['input'];
  exitSpotMiles?: InputMaybe<Scalars['Int']['input']>;
  jumpRun?: InputMaybe<Scalars['Int']['input']>;
  offsetDirection?: InputMaybe<Scalars['String']['input']>;
  offsetMiles?: InputMaybe<Scalars['Int']['input']>;
  temperature?: InputMaybe<Scalars['Int']['input']>;
  winds?: InputMaybe<Scalars['String']['input']>;
};

export type Wind = {
  __typename?: 'Wind';
  altitude?: Maybe<Scalars['String']['output']>;
  direction?: Maybe<Scalars['String']['output']>;
  speed?: Maybe<Scalars['String']['output']>;
  temperature?: Maybe<Scalars['String']['output']>;
};
