version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3-node
    steps:
      - checkout
      - ruby/install-deps
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.3-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: openmanifest_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
