query AllowedTicketTypes($dropzoneId: Int!, $onlyPublicTickets: Boolean) {
  dropzone(id: $dropzoneId) {
    id

    ticketTypes(isPublic: $onlyPublicTickets) {
      ...ticketTypeEssentials

      extras {
        id
        cost
        name
      }
    }
  }
}

query QueryTicketType($dropzoneId: Int!) {
    dropzone(id: $dropzoneId) {
      id
      ticketTypes {
        ...ticketTypeEssentials
      }
    }
  }