#import "../fragments/dropzoneUsers.fragments.gql"
query QueryDropzoneUserProfile($dropzoneId: Int!, $dropzoneUserId: Int!) {
  dropzone(id: $dropzoneId) {
    id
    name

    dropzoneUser(id: $dropzoneUserId) {
      ...dropzoneUserProfile
    }
  }
}
