query QueryDropzones($isPublic: Boolean, $requestedPublication: Boolean) {
  dropzones(isPublic: $isPublic, requestedPublication: $requestedPublication) {
    edges {
      node {
        ...dropzoneEssentials
      }
    }
  }
}