query AllowedTicketTypes($dropzone: Int!, $onlyPublicTickets: Boolean) {
  dropzone(id: $dropzone) {
    id

    ticketTypes(isPublic: $onlyPublicTickets) {
      ...ticketTypeEssentials

      extras {
        id
        cost
        name
      }
    }
  }
}

query TicketTypes($dropzone: Int!, $allowManifestingSelf: Boolean) {
  ticketTypes(dropzone: $dropzone, allowManifestingSelf: $allowManifestingSelf) {
    ...ticketTypeEssentials
  }
}