query AllowedTicketTypes($dropzoneId: Int!, $onlyPublicTickets: Boolean) {
  dropzone(id: $dropzoneId) {
    id

    ticketTypes(isPublic: $onlyPublicTickets) {
      ...ticketTypeEssentials

      extras {
        id
        cost
        name
      }
    }
  }
}

query TicketTypes($dropzoneId: Int!, $allowManifestingSelf: Boolean) {
  ticketTypes(dropzoneId: $dropzoneId, allowManifestingSelf: $allowManifestingSelf) {
    ...ticketTypeEssentials
  }
}