#import "./orders.fragments.gql"
#import "./transactions.fragments.gql"
#import "./users.fragments.gql"

fragment currentUserEssentials on DropzoneUser {
  id
  credits
  hasCredits
  hasExitWeight
  hasMembership
  hasReserveInDate
  hasRigInspection
  hasLicense
  permissions
  expiresAt

  role {
    id
    name
  }
}

fragment currentUserDetailed on DropzoneUser {
  ...currentUserEssentials,

  user {
    ...userEssentials
  }


  rigInspections {
    id
    isOk
    inspectedBy {
      id
      user {
        id
        name
      }
    }
    rig {
      id
    }
  }

  orders {
    edges {
      node {
        ...orderEssentials
      }
    }
  }
  availableRigs {
    name
    id
    make
    model
    canopySize
    serial

    user {
      id
    }
  }
  license {
    id
    name
  }

  user {
    id
    name
    exitWeight
    email
    phone
    pushToken
    image

    rigs {
      id
      name
      model
      make
      serial
      canopySize
      repackExpiresAt
      packingCard

      user {
        id
      }
    }
    jumpTypes {
      id
      name
    }
    license {
      id
      name
    }
  }
}