fragment currentUserEssentials on DropzoneUser {
  id
  credits
  hasCredits
  hasExitWeight
  hasMembership
  hasReserveInDate
  hasRigInspection
  hasLicense
  permissions
  expiresAt

  role {
    id
    name
  }
}

fragment currentUserDetailed on DropzoneUser {
  ...currentUserEssentials,
  rigInspections {
    id
    isOk
    inspectedBy {
      id
      user {
        id
        name
      }
    }
    rig {
      id
    }
  }

  orders {
    edges {
      node {
        id
        title
        state
        createdAt
        title
        amount
        buyer {
          __typename
          ... on DropzoneUser {
            id
            user {
              id
              name
            }
          }
          ... on Dropzone {
            id
            name
          }
        }
        seller {
          __typename
          ... on DropzoneUser {
            id
            user {
              id
              name
            }
          }
          ... on Dropzone {
            id
            name
          }
        }
        item {
          title
          cost

          ... on Slot {
            id

            ticketType {
              id
              name
              cost
            }

            extras {
              id
              name
              cost
            }
          }
          ... on TicketType {
            id
          }
          ... on Extra {
            id
            name
          }
        }
        receipts {
          id
          transactions {
            id
            message
            transactionType
            status
            createdAt
            amount
            sender {
              ... on DropzoneUser {
                id
                user {
                  id
                  name
                }
              }
              ... on Dropzone {
                id
                name
              }
            }
            receiver {
              ... on DropzoneUser {
                id
                user {
                  id
                  name
                }
              }
              ... on Dropzone {
                id
                name
              }
            }
          }
        }
      }
    }
  }
  availableRigs {
    name
    id
    make
    model
    canopySize
    serial

    user {
      id
    }
  }

  license {
    id
    name
  }

  user {
    id
    name
    exitWeight
    email
    phone
    pushToken
    image

    rigs {
      id
      name
      model
      make
      serial
      canopySize
      repackExpiresAt
      packingCard

      user {
        id
      }
    }
    jumpTypes {
      id
      name
    }
    license {
      id
      name
    }
  }
}