#import "./currentuser.fragments.gql";
fragment dropzoneEssentials on Dropzone {
  id
  lat
  lng
  name
  primaryColor
  secondaryColor
  isPublic
  requestPublication
  banner
  isCreditSystemEnabled
}

fragment dropzoneDetailed on Dropzone {
  ...dropzoneEssentials,

  federation {
    id
    name
    slug
  }

  planes {
    ...planeEssentials
  }
  ticketTypes {
    ...ticketTypeEssentials
  }

  currentConditions {
    ...weatherConditionEssentials
  }
  loads(earliestTimestamp: $earliestTimestamp) {
    edges {
      node {
        id
        name
        loadNumber
        isOpen
        maxSlots
        state
      }
    }
  }
}

fragment dropzoneExtensive on Dropzone {
  ...dropzoneDetailed

  currentUser {
    ...currentUserDetailed
  }
}