fragment dropzoneUserEssentials on DropzoneUser {
  id
  role {
    id
    name
  }
  license {
    id
    name
  }
  user {
    ...userEssentials
  }
}

fragment dropzoneUserDetails on DropzoneUser {
  id
  role {
    id
    name
  }
  license {
    id
    name
  }
  user {
    ...userDetailed
  }
  availableRigs {
    ...rigEssentials
  }
}

fragment dropzoneUserProfile on DropzoneUser {
  id
  credits
  expiresAt
  permissions

  role {
    id
    name
  }
  availableRigs {
    id
    name
    model
    make
    serial
    canopySize
    repackExpiresAt
  }

  user {
    id
    name
    exitWeight
    email
    phone
    image
    rigs {
      id
      name
      model
      make
      serial
      canopySize
      repackExpiresAt
    }
    jumpTypes {
      id
      name
    }
    license {
      id
      name
      federation {
        id
        name
      }
    }
  }

  slots {
    edges {
      node {
        id
        createdAt
        load {
          id
          name
          loadNumber
          dispatchAt
          createdAt
        }
        jumpType {
          id
          name
        }
        ticketType {
          id
          name
        }
      }
    }
  }
}