fragment dropzoneUserEssentials on DropzoneUser {
  id
  role {
    id
    name
  }
  license {
    id
    name
  }
  user {
    ...userEssentials
  }
}

fragment dropzoneUserDetails on DropzoneUser {
  id
  role {
    id
    name
  }
  license {
    id
    name
  }
  user {
    ...userDetailed
  }
  availableRigs {
    ...rigEssentials
  }
}

fragment dropzoneUserProfile on DropzoneUser {
  id
  credits
  expiresAt
  permissions

  role {
    id
    name
  }
  availableRigs {
    ...rigEssentials
  }
  rigInspections {
    ...rigInspectionEssentials
  }

  user {
    ...userDetailed
  }

  orders {
    edges {
      node {
        ...orderEssentials
      }
    }
  }

  slots {
    edges {
      node {
        ...slotEssentials
      }
    }
  }
}