fragment rigEssentials on Rig {
  id
  name
  make
  model
  serial
  canopySize
  repackExpiresAt
  packValue
  maintainedAt
  rigType
  packingCard
  isPublic

  user {
    id
    name
  }
  dropzone {
    id
  }
}

fragment userRigDetailed on Rig {
  ...rigEssentials

  user {
    id
    rigs {
      ...rigEssentials
    }
  }
}