fragment slotDetails on Slot {
  id
  createdAt
  exitWeight
  passengerName
  passengerExitWeight
  wingLoading
  dropzoneUser {
    ...dropzoneUserEssentials
  }
  ticketType {
    ...ticketTypeEssentials
  }
  jumpType {
    ...jumpTypeEssentials
  }
  extras {
    id
    name
  }
}
