fragment slotEssentials on Slot {
  id
  createdAt
  exitWeight
  passengerName
  passengerExitWeight
  wingLoading
  groupNumber
  ticketType {
    ...ticketTypeEssentials
  }
  jumpType {
    ...jumpTypeEssentials
  }
  extras {
    id
    name
  }
}

fragment slotDetails on Slot {
  ...slotEssentials
  rig {
    ...rigEssentials
  }
  dropzoneUser {
    ...dropzoneUserEssentials
  }
}

fragment slotExhaustive on Slot {
  ...slotDetails
  dropzoneUser {
    ...dropzoneUserDetails
  }
  load {
    ...loadDetails
  }
  rig {
    ...rigEssentials
  }
}
