fragment userEssentials on User {
  id
  name
  nickname
  phone
  email
  exitWeight
  moderationRole
  image
  apfNumber
  license {
    id
    name
  }
}

fragment userDetailed on User {
  ...userEssentials
  rigs {
    ...userRigDetailed
  }
}