name: Publish production
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  publish-web-production:
    name: Publish Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn ts:graphql:production && yarn typecheck
        name: Ensure server compatibility
      - run: yarn web:build:production
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build-prod
          external_repository: OpenManifest/openmanifest-web
          cname: openmanifest.org
  publish-expo-production:
    name: Publish Expo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn ts:graphql:production && yarn typecheck
        name: Ensure server compatibility
      - run: yarn expo:publish:prod
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          EXPO_ENV: production
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
