name: Publish staging
on:
  push:
    branches:
      - main
jobs:
  publish-web-staging:
    name: Publish Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn ts:graphql:staging && yarn typecheck
        name: Ensure server compatibility
      - run: yarn web:build:staging
        env:
          GOOGLE_MAPS_WEB: ${{ secrets.GOOGLE_MAPS_WEB }}
          GOOGLE_MAPS_IOS: ${{ secrets.GOOGLE_MAPS_IOS }}
          GOOGLE_MAPS_ANDROID: ${{ secrets.GOOGLE_MAPS_ANDROID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_API_KEY: ${{ secrets.SENTRY_API_KEY }}
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./web-build-staging
          deploy_key: ${{ secrets.WEB_DEPLOY_KEY_STAGING }}
          external_repository: OpenManifest/openmanifest-web-staging
          cname: staging.openmanifest.org
  publish-expo-staging:
    name: Publish Expo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: yarn ts:graphql:staging && yarn typecheck
        name: Ensure server compatibility
      - run: yarn expo:publish:staging
        env:
          GOOGLE_MAPS_WEB: ${{ secrets.GOOGLE_MAPS_WEB }}
          GOOGLE_MAPS_IOS: ${{ secrets.GOOGLE_MAPS_IOS }}
          GOOGLE_MAPS_ANDROID: ${{ secrets.GOOGLE_MAPS_ANDROID }}
          NODE_OPTIONS: --max_old_space_size=4096
          EXPO_ENV: staging
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_API_KEY: ${{ secrets.SENTRY_API_KEY }}
          APPSIGNAL_STAGING_API_KEY: ${{ secrets.APPSIGNAL_STAGING_API_KEY }}
