name: Lint & Test
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  eslint-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Use NodeJS
        with:
          node-version: "14"
      - name: Setup Python for JUnit Parsing
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Configure npm
        run: npm config set unsafe-perm true
      - name: Install yarn
        run: npm install -g yarn
      - name: Print path
        run: yarn config get cacheFolder
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install modules
        run: yarn
      - name: eslint
        run: yarn lint:ci --output-file ~/reports/eslint.xml
      - uses: actions/upload-artifact@v2
        with:
          name: eslint
          path: ~/reports/eslint.xml
      - name: jest
        run: yarn test:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: ~/reports
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: ~/reports/*.xml
